// ─── Notebook Export & Multi-File Split Service ──────────────────────────────
// Splits notebook code cells into individual language files (java_01.java, java_02.java, etc.)
// packaged inside a dedicated language folder (.zip) or extracted to the workspace.

import JSZip from 'jszip';
import { syncJavaClassWithFilename, sanitizeFilenameIdentifier } from './identifierSanitizer';

/**
 * Maps a notebook language key to its folder name and standard file extension
 */
export function getLanguageFolderAndExt(langKey = 'python') {
  const l = String(langKey || 'python').toLowerCase();
  if (l.includes('java') && !l.includes('script')) {
    return { folder: 'java', ext: 'java', name: 'Java' };
  }
  if (l.includes('cpp') || l.includes('c++')) {
    return { folder: 'cpp', ext: 'cpp', name: 'C++' };
  }
  if (l.includes('javascript') || l === 'js') {
    return { folder: 'javascript', ext: 'js', name: 'JavaScript' };
  }
  if (l.includes('typescript') || l === 'ts') {
    return { folder: 'typescript', ext: 'ts', name: 'TypeScript' };
  }
  if (l === 'c') {
    return { folder: 'c', ext: 'c', name: 'C' };
  }
  if (l.includes('sql')) {
    return { folder: 'sql', ext: 'sql', name: 'SQL' };
  }
  return { folder: 'python', ext: 'py', name: 'Python' };
}

/**
 * Normalizes cell source (string or array of strings)
 */
function getCellSource(cell) {
  if (Array.isArray(cell?.source)) {
    return cell.source.join('');
  }
  return cell?.source || '';
}

/**
 * Splits all notebook cells into structured standalone files
 * e.g. java_01.java, java_02.java, notes_01.md
 */
export function splitNotebookCells(notebook, langKey = 'python') {
  const { folder, ext, name } = getLanguageFolderAndExt(langKey);
  const cells = notebook?.cells || [];

  const files = [];
  let codeIndex = 0;
  let mdIndex = 0;

  for (let i = 0; i < cells.length; i++) {
    const cell = cells[i];
    const source = getCellSource(cell).trim();
    if (!source) continue;

    if (cell.cell_type === 'code') {
      codeIndex++;
      const paddedNum = String(codeIndex).padStart(2, '0');
      const fileName = `${folder}_${paddedNum}.${ext}`;

      let processedSource = source;
      // For Java: if there's a public class, ensure it matches Java_01 or is runnable
      if (ext === 'java') {
        processedSource = syncJavaClassWithFilename(processedSource, fileName);
      }

      files.push({
        fileName,
        folderPath: folder,
        relativePath: `${folder}/${fileName}`,
        content: processedSource,
        type: 'code',
        index: codeIndex,
      });
    } else if (cell.cell_type === 'markdown') {
      mdIndex++;
      const paddedNum = String(mdIndex).padStart(2, '0');
      const fileName = `notes_${paddedNum}.md`;
      files.push({
        fileName,
        folderPath: folder,
        relativePath: `${folder}/${fileName}`,
        content: source,
        type: 'markdown',
        index: mdIndex,
      });
    }
  }

  // If no code cells exist, provide at least one template file
  if (files.length === 0) {
    const fileName = `${folder}_01.${ext}`;
    files.push({
      fileName,
      folderPath: folder,
      relativePath: `${folder}/${fileName}`,
      content: `// ${name} File 01\n`,
      type: 'code',
      index: 1,
    });
  }

  return {
    folder,
    ext,
    languageName: name,
    files,
    codeCount: codeIndex,
    mdCount: mdIndex,
  };
}

/**
 * Exports notebook as a structured ZIP archive containing the language folder
 * (e.g. java/java_01.java, java/java_02.java, java/README.md)
 */
export async function exportNotebookAsSplitZip(notebook, baseFileName = 'notebook', langKey = 'python') {
  const { folder, files, languageName, codeCount, mdCount } = splitNotebookCells(notebook, langKey);
  const zip = new JSZip();

  // Create language folder inside the ZIP
  const langFolder = zip.folder(folder);

  // Add all split cell files
  files.forEach((file) => {
    langFolder.file(file.fileName, file.content);
  });

  // Create an informative README.md
  const readmeContent = `# ${languageName} Workspace Split Export
Generated by FullCode Online Compiler & Interactive Notebooks.

## Export Summary
- **Language**: ${languageName}
- **Folder**: \`${folder}/\`
- **Total Code Files**: ${codeCount}
- **Documentation / Markdown Files**: ${mdCount}

## Included Files:
${files.map((f) => `- \`${f.relativePath}\` (${f.type === 'code' ? 'Code File' : 'Documentation'})`).join('\n')}

---
*Created on ${new Date().toLocaleString()}*
`;

  langFolder.file('README.md', readmeContent);

  // Also include the original .ipynb for complete portability
  const rawJson = JSON.stringify(notebook, null, 2);
  zip.file(`${folder}_notebook.ipynb`, rawJson);

  // Generate ZIP blob and trigger browser download
  const blob = await zip.generateAsync({ type: 'blob' });
  const cleanBase = baseFileName.replace(/\.ipynb$/i, '');
  const zipFileName = `${cleanBase}_${folder}_export.zip`;

  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = zipFileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);

  return { zipFileName, fileCount: files.length };
}

/**
 * Extracts all split notebook cells directly into the active browser workspace
 * creating folder/java_01.java, etc. in the File Explorer
 */
export function extractNotebookToWorkspace(notebook, langKey, handleAddFile, showToast) {
  const { folder, files, languageName } = splitNotebookCells(notebook, langKey);

  let addedCount = 0;
  files.forEach((file) => {
    handleAddFile?.(file.relativePath, file.content, null, false);
    addedCount++;
  });

  showToast?.(`Extracted ${addedCount} files into workspace folder "${folder}/" 📁`);
  return { folder, addedCount };
}
